### ISSUE TITLE
User can click buttons while busy bee active

### ISSUE THREAD

**Issue by underscoredotspace** [underscoredotspace/messy.cloud#24]
Not a good look

**Comment by tusharsrivastava** [comment]
A simple `pointer-events: none;` in `.busy-bee` class in `index.scss` can solve this issue. What do you say?

**Comment by underscoredotspace** [comment]
Thank you for this suggestion @tusharsrivastava, however that seems to remove the custom cursor althogether (at least on firefox). Food for though though 👌

**Comment by tusharsrivastava** [comment]
Hmm!
Then we might need an overlay div solution with:
```css
position: fixed;
top: 0;
left: 0;
right: 0;
bottom: 0;
z-index: 99999;
```
Need to display it when class `busy-bee` is active on body.
